= Welcome to {lab_name}!

== Introduction

Veeam Kasten is a Kubernetes-native data protection platform designed to secure, manage, and recover containerized applications and VMs, offering a unified approach to backup, disaster recovery, and application mobility. By leveraging OpenShift’s hybrid cloud infrastructure, Kasten ensures consistent data protection policies across environments, enabling organizations to meet compliance requirements and maintain business continuity with minimal operational overhead.

In this lab we will explore disaster recovery, backup and restore of Virtual Machines (Module 1) and Containers (Module 2) on OpenShift using the Veeam Kasten product.

== What Content Is Covered In The Lab?

=== Module 1 - Protecting Virtual Machines on OpenShift with Veeam Kasten

* _Installing Veeam Kasten_: In this section we will provide a review of how to install the product on any OpenShift cluster. Since the product is already installed in the lab environment this sectionwill be a review only.

* _Creating Location Profiles_: In this section, we will use setup the Kasten K10 product with a location profile to specify storage for the virtual machine backups.

* _Protecting Virtual Machines_: In this section we will perform several backup and restore operations with virtual machines.

* _Optional: Configuring Multi Cluster_: In this section you will learn how to set up Kasten Multi-Cluster Manager. Since our lab environment is a single cluster this section will be review only.

* _Optional: Migrating Workloads_: This section addresses restoring backups to different clusters. Since our lab environment is a single cluster this section will be review only.

=== Module 2 - Protecting Containerized Workloads with Veeam Kasten

* _Deploy a Sample Application_: In this section we will deploy a sample application to OpenShift.

* _Configure Kasten for Backup_: In this section we will configure Kasten to use an S3-compatible object store for backup.

* _Backup and Recover our Application_: In this section we will perform backup and recovery operations on the sample application.

* _Provide Application Consistent Backups via Kasten Blueprints_: In this section we will explore how to use Kasten Blueprints to provide application consistent backups of our sample application.

== Version Information

This edition of the lab has been developed using the following software versions:

* Red Hat OpenShift 4.18.x
* Red Hat OpenShift Virtualization 4.18.x
* Veeam Kasten K10 {k10_version}

== Requirements for the Lab Environment

* Participant needs to have their own computer with browser and internet access.
* Chromium based browsers are recommended as some copy/paste functions don't work in Firefox for the time being.
* Remote access console uses the US keyboard layout by default, so it's good to know where special characters reside for other country's layouts, or to use the copy/paste function in a supported browser.

=== Credentials for the OpenShift Console

* Your OpenShift cluster console is available {openshift_console_url}[here^].
* Your Kasten K10 Dashboard is available {kasten_dashboard}[here^].

Your credentials for both are:

* *User:* {user}
* *Password:* {password}

=== Important information about your User

====
[NOTE]

All screenshots in the following lab guides reference *user1*. Please make sure to follow the *text* to ensure you use the correct user that has been assigned to you! Additionally your user is limited to your namespace, so ensure when trying to view or edit resources in OpenShift, you do so in your user's namespace: backuptarget-{user}
====
